Update README.md
ui5-community/ui5-ecosystem-showcase pull request #1034
Opened 2024-07-17 09:09 UTC by nicoschoenteich

Shouldn't this say `false`? It set to `true`, it will only generate the zip.

2024-07-17 09:20 UTC, nicoschoenteich commented
Updated the commit message, the check still fails though, as it wouldn't pick up the new message.

2024-07-19 19:03 UTC, petermuessig requested changes

2024-07-19 19:03 UTC, petermuessig commented on packages/ui5-task-zipper/README.md
> +Set this to `false` if you also want to generate the unzipped resources in the `dist` folder. Otherwise, it will only create the zipped archive.
I would even phrase this completely different:

Set this to `true` to omit the resources contained in the zip from the build result (typically in the `dist` folder). By default, the build result contains all resources and the zip.

2024-07-19 19:05 UTC, petermuessig commented
Can you please rebase to verify if the commit message issue still exists?

2024-07-22 19:10 UTC, merged

2024-07-22 19:11 UTC, petermuessig commented
THX