feat(ui5-stringreplace): create new module ui5-stringreplace
ui5-community/ui5-ecosystem-showcase pull request #680
Opened 2023-01-26 14:30 UTC by dominikfeininger

merging:
- ui5-task-stringrepalce
- ui5-middleware-stringreplace

follow up from #304

2023-02-06 07:53 UTC, petermuessig requested changes
Besides some small findings, it looks good!

Once fixed, we can merge => 👍 

THX, Dominik

2023-02-06 07:53 UTC, petermuessig commented on README.md
> +└── ui5-tooling-stringreplace      // tooling extension: replaces placeholder strings
`s` comes before `t` 😉

2023-02-06 07:53 UTC, petermuessig commented on README.md
> +* https://www.npmjs.com/package/ui5-tooling-stringreplace
same here - alphabetic order

2023-02-06 07:53 UTC, petermuessig commented on README.md
> +| [ui5-tooling-stringreplace](packages/ui5-tooling-stringreplace/README.md) | stringreplace resources using Babel | [![npm version](https://badge.fury.io/js/ui5-tooling-stringreplace.svg)](https://ba
again - alphabetic order

2023-02-06 07:53 UTC, petermuessig commented on packages/ui5-app/package.json
> +    "ui5-tooling-stringreplace": "^0.0.1",
`s` comes after `m`

2023-02-06 07:53 UTC, petermuessig commented on packages/ui5-app/package.json
> +      "ui5-tooling-stringreplace",
like above

2023-02-06 07:53 UTC, petermuessig commented on packages/ui5-tooling-stringreplace/lib/middleware.js
>  const log = require("@ui5/logger").getLogger("server:custommiddleware:stringreplacer");
`stringreplacer` should renamed to `stringreplace`

2023-02-06 07:53 UTC, petermuessig commented on packages/ui5-tooling-stringreplace/lib/task.js
> +const log = require("@ui5/logger").getLogger("builder:customtask:stringreplacer");
`stringreplacer` should renamed to `stringreplace`

2023-02-06 07:53 UTC, petermuessig commented on packages/ui5-tooling-stringreplace/lib/task.js
> +	if (options.configuration) {
Can be simplified today like this:

```
option.configuration?.replace?.forEach((entry) => {
```

2023-02-06 07:55 UTC, petermuessig commented
@dominikfeininger : Maybe you can also take a look into #339 and include this into the change?

2023-02-06 09:07 UTC, dominikfeininger commented
Hi, I noticed there is neither an execution of the `ui5-tooling-stringreplace-middleware` nor `ui5-tooling-stringreplace-task` in the executed pipeline tests. At a first glance this seems to apply for other modules as well. IMHO each module should be executed at least once during the pipeline tests.

2023-02-06 10:58 UTC, dominikfeininger commented
- merged:
 ui5-task-stringrepalce
 ui5-middleware-stringreplace
- add custom `prefix` option in ui5.yaml configuration

2023-02-07 15:12 UTC, petermuessig approved these changes
LGTM - thanks for the adoption...

2023-02-07 15:13 UTC, merged