fix: improvements of projects for tooling 3.0
ui5-community/ui5-ecosystem-showcase pull request #696
Opened 2023-03-19 22:11 UTC by petermuessig

build: always use chromedriver matching the environment

chore: added simple app using tooling 3.0

fix: fixed the tsconfig.json of TS projects

fix: updated UI5 version

fix(ui5-task-minify-xml): add tooling 3.0 dependency determination

fix(ui5-tooling-modules): only rely on workspace dependencies (to find entry points)

fix(ui5-tooling-modules): improved logging

fix(ui5-task-compileless): fixed dependency determination (theme build requires all deps)

2023-03-19 22:13 UTC, petermuessig commented
@flovogt : 
* found out that the less task requires all dependencies, similar like the library build (btw: this is also the reason why the ui5-app runs the build on all dependencies)
* one task was missing: the minify xml task 
* added a very simple app to validate the tooling 3.0 with the two most important middlewares/tasks: ui5-tooling-modules and ui5-tooling-transpile - maybe the proxy would be another interesting one... 
* some more small bugfixes and cleanups

2023-03-20 07:49 UTC, flovogt requested changes
Hi @petermuessig,
thanks a lot addressing all these points.

> found out that the less task requires all dependencies, similar like the library build (btw: this is also the reason why the ui5-app runs the build on all dependencies)

Ack, Thx for fixing

__________

> one task was missing: the minify xml task

Ack. Thx for fixing

__________

> added a very simple app to validate the tooling 3.0 with the two most important middlewares/tasks: ui5-tooling-modules and ui5-tooling-transpile - maybe the proxy would be another interesting one...

Ack.

__________


> some more small bugfixes and cleanups

Ack.

I have only minor comments

2023-03-20 07:49 UTC, flovogt commented on packages/ui5-app-simple/webapp/index.html
> +		<!-- div data-sap-ui-component data-url="./" data-name="ui5.ecosystem.demo.simpleapp" data-id="container" data-settings='{"id" : "Sample"}'></div -->
AFAIS This commented code can be removed.

2023-03-20 07:49 UTC, flovogt commented on packages/ui5-tooling-modules/lib/middleware.js
> +//const {parse, print} = require("recast");
AFAIS this code can be removed.

2023-03-20 08:06 UTC, flovogt approved these changes
LGTM 🎊

2023-03-20 08:14 UTC, merged